// Il catalogo fisso dei controlli: le stesse voci, nello stesso ordine, nel
// report compilato e nel modello vuoto. `peso` pesa la voce nel punteggio della
// sua area; `impatto` ordina il piano d'azione; `perche` e `soluzione` sono le
// frasi che il titolare legge nelle priorità.

export const AREE = [
  { id: 'velocita', nome: 'Velocità', peso: 25, sottotitolo: 'Quanto aspetta chi apre il sito' },
  { id: 'mobile', nome: 'Esperienza da smartphone', peso: 15, sottotitolo: 'Come vi vede chi vi cerca dal telefono' },
  { id: 'seo', nome: 'Visibilità su Google', peso: 20, sottotitolo: 'Quanto è facile trovarvi' },
  { id: 'gbp', nome: 'Google Business e recensioni', peso: 20, sottotitolo: 'La vostra vetrina su Maps' },
  { id: 'sicurezza', nome: 'Sicurezza e conformità', peso: 10, sottotitolo: 'Fiducia, privacy e obblighi di legge' },
  { id: 'conversione', nome: 'Contatti e integrazioni', peso: 10, sottotitolo: 'Quanto è facile diventare clienti' },
];

export const CONTROLLI = [
  // ── Esperienza da smartphone ─────────────────────────────────────────────
  { id: 'm_viewport', area: 'mobile', peso: 2, impatto: 3, nome: 'Pagina adattata allo schermo del telefono',
    perche: 'Senza adattamento il sito appare rimpicciolito e costringe a zoomare.',
    soluzione: 'Layout responsive progettato prima per lo smartphone.' },
  { id: 'm_popup', area: 'mobile', peso: 2, impatto: 3, nome: 'Prima schermata libera da pop-up',
    perche: 'Se la prima cosa che si vede è un muro di testo, molti chiudono la pagina.',
    soluzione: 'Banner dei consensi discreto e prima schermata pulita.' },
  { id: 'm_overflow', area: 'mobile', peso: 1, impatto: 2, nome: 'Nessuno scorrimento laterale',
    perche: 'Elementi che escono dallo schermo fanno sembrare il sito rotto.',
    soluzione: 'Correzione degli elementi che sforano la larghezza dello schermo.' },
  { id: 'm_font', area: 'mobile', peso: 1, impatto: 2, nome: 'Testi leggibili senza zoom',
    perche: 'Testi troppo piccoli stancano e fanno abbandonare la lettura.',
    soluzione: 'Tipografia studiata per la lettura da telefono.' },
  { id: 'm_tap', area: 'mobile', peso: 1, impatto: 2, nome: 'Pulsanti facili da toccare',
    perche: 'Link piccoli e vicini fanno sbagliare il tocco e spazientiscono.',
    soluzione: 'Pulsanti ampi e distanziati, pensati per il pollice.' },
  { id: 'm_call', area: 'mobile', peso: 2, impatto: 3, nome: 'Chiamata con un tocco',
    perche: 'Da telefono chi vuole chiamare non deve copiare il numero a mano.',
    soluzione: 'Pulsante “Chiama” sempre raggiungibile.' },
  { id: 'm_whatsapp', area: 'mobile', peso: 1, impatto: 2, nome: 'Contatto WhatsApp diretto',
    perche: 'Molti clienti preferiscono scrivere una domanda veloce su WhatsApp.',
    soluzione: 'Pulsante WhatsApp con messaggio già impostato.' },
  { id: 'm_immagini', area: 'mobile', peso: 1, impatto: 2, nome: 'Immagini leggere e nel formato giusto',
    perche: 'Foto pesanti consumano dati e rallentano ogni pagina.',
    soluzione: 'Immagini in formato moderno (WebP/AVIF) e dimensionate per lo schermo.' },
  { id: 'm_a11y', area: 'mobile', peso: 1, impatto: 1, nome: 'Accessibilità (contrasti, etichette, lettura)',
    perche: 'Un sito accessibile è più chiaro per tutti, non solo per chi ha difficoltà.',
    soluzione: 'Contrasti, etichette e struttura secondo le linee guida WCAG.' },

  // ── Visibilità su Google ─────────────────────────────────────────────────
  { id: 's_titolo', area: 'seo', peso: 2, impatto: 3, nome: 'Titolo della pagina con attività e città',
    perche: 'È la riga blu che si legge su Google: decide se vi cliccano.',
    soluzione: 'Titoli scritti per chi cerca, con attività e città.' },
  { id: 's_descrizione', area: 'seo', peso: 1, impatto: 2, nome: 'Descrizione per i risultati di Google',
    perche: 'Senza, Google mostra frasi prese a caso dalla pagina.',
    soluzione: 'Descrizioni persuasive per ogni pagina importante.' },
  { id: 's_h1', area: 'seo', peso: 1, impatto: 2, nome: 'Un titolo principale (H1) chiaro',
    perche: 'Aiuta Google a capire di cosa parla la pagina.',
    soluzione: 'Struttura dei titoli ordinata, uno principale per pagina.' },
  { id: 's_alt', area: 'seo', peso: 1, impatto: 1, nome: 'Immagini descritte (testo alternativo)',
    perche: 'Le foto dei vostri gioielli possono comparire su Google Immagini.',
    soluzione: 'Descrizioni per ogni immagine di prodotto.' },
  { id: 's_indicizzabile', area: 'seo', peso: 2, impatto: 3, nome: 'Pagina indicizzabile da Google',
    perche: 'Se Google non può leggerla, la pagina non esiste nelle ricerche.',
    soluzione: 'Impostazioni di indicizzazione corrette.' },
  { id: 's_sitemap', area: 'seo', peso: 1, impatto: 1, nome: 'Mappa del sito (sitemap.xml)',
    perche: 'Indica a Google tutte le pagine da mostrare.',
    soluzione: 'Sitemap generata e inviata a Search Console.' },
  { id: 's_robots', area: 'seo', peso: 1, impatto: 1, nome: 'File robots.txt',
    perche: 'Guida i motori di ricerca tra le pagine del sito.',
    soluzione: 'File robots.txt corretto.' },
  { id: 's_canonical', area: 'seo', peso: 1, impatto: 1, nome: 'Indirizzo canonico dichiarato',
    perche: 'Evita che Google veda la stessa pagina due volte e la penalizzi.',
    soluzione: 'Canonical su ogni pagina.' },
  { id: 's_schema', area: 'seo', peso: 2, impatto: 2, nome: 'Dati strutturati di attività locale',
    perche: 'Dicono a Google indirizzo, orari e categoria in un linguaggio che capisce.',
    soluzione: 'Schema.org LocalBusiness / JewelryStore completo.' },
  { id: 's_social', area: 'seo', peso: 1, impatto: 2, nome: 'Anteprima quando il link viene condiviso',
    perche: 'Senza, su WhatsApp e social il link appare senza foto né titolo.',
    soluzione: 'Anteprime Open Graph curate per ogni pagina.' },
  { id: 's_locale', area: 'seo', peso: 1, impatto: 2, nome: 'Città e indirizzo scritti nel sito',
    perche: 'Google collega il sito alla città solo se la trova scritta.',
    soluzione: 'Indirizzo, città e zona serviti in chiaro.' },
  { id: 's_posizione', area: 'seo', peso: 3, impatto: 3, nome: 'Posizione nei risultati di Google',
    perche: 'Oltre la prima pagina vi trova meno di una persona su cento.',
    soluzione: 'Strategia SEO locale su pagine, contenuti e scheda Google.' },
  { id: 's_mappe', area: 'seo', peso: 3, impatto: 3, nome: 'Presenza nei primi 3 risultati su Maps',
    perche: 'Il riquadro con la mappa prende la maggior parte dei clic locali.',
    soluzione: 'Ottimizzazione della scheda Google e delle recensioni.' },

  // ── Google Business e recensioni ─────────────────────────────────────────
  { id: 'g_scheda', area: 'gbp', peso: 3, impatto: 3, nome: 'Scheda presente e rivendicata',
    perche: 'Senza controllo della scheda, chiunque può suggerire modifiche.',
    soluzione: 'Rivendicazione e verifica della scheda.' },
  { id: 'g_categoria', area: 'gbp', peso: 1, impatto: 2, nome: 'Categoria principale corretta',
    perche: 'È il primo criterio con cui Google decide per quali ricerche mostrarvi.',
    soluzione: 'Categoria principale e secondarie ottimizzate.' },
  { id: 'g_orari', area: 'gbp', peso: 1, impatto: 2, nome: 'Orari completi e aggiornati',
    perche: 'Orari sbagliati significano clienti davanti alla serranda chiusa.',
    soluzione: 'Orari, festivi e aperture straordinarie sempre aggiornati.' },
  { id: 'g_contatti', area: 'gbp', peso: 1, impatto: 2, nome: 'Telefono e sito collegati',
    perche: 'Ogni passaggio in più tra la scheda e voi è un cliente perso.',
    soluzione: 'Collegamenti diretti a telefono, sito e WhatsApp.' },
  { id: 'g_foto', area: 'gbp', peso: 1, impatto: 2, nome: 'Foto recenti e curate (almeno 20)',
    perche: 'Le schede con molte foto ricevono molte più richieste di indicazioni.',
    soluzione: 'Servizio fotografico di vetrina, negozio e creazioni.' },
  { id: 'g_descrizione', area: 'gbp', peso: 1, impatto: 1, nome: 'Descrizione dell’attività',
    perche: 'Racconta chi siete a chi non vi conosce ancora.',
    soluzione: 'Descrizione scritta con le parole che usano i clienti.' },
  { id: 'g_post', area: 'gbp', peso: 1, impatto: 1, nome: 'Aggiornamenti negli ultimi 30 giorni',
    perche: 'Una scheda attiva segnala a Google e ai clienti che siete presenti.',
    soluzione: 'Calendario di post: novità, collezioni, eventi.' },
  { id: 'g_prodotti', area: 'gbp', peso: 1, impatto: 1, nome: 'Prodotti e servizi inseriti',
    perche: 'Mostrano cosa trovate in negozio prima ancora della visita.',
    soluzione: 'Catalogo prodotti e servizi nella scheda.' },
  { id: 'g_valutazione', area: 'gbp', peso: 2, impatto: 3, nome: 'Valutazione media di almeno 4,5',
    perche: 'Sotto il 4,5 molti clienti scelgono il concorrente accanto.',
    soluzione: 'Strategia per raccogliere recensioni dai clienti soddisfatti.' },
  { id: 'g_numero', area: 'gbp', peso: 2, impatto: 2, nome: 'Numero di recensioni competitivo',
    perche: 'Il numero di recensioni pesa sul posizionamento quanto il voto.',
    soluzione: 'QR code in negozio e messaggio dopo l’acquisto.' },
  { id: 'g_risposte', area: 'gbp', peso: 2, impatto: 3, nome: 'Risposte del titolare alle recensioni',
    perche: 'Chi legge le recensioni guarda soprattutto come rispondete.',
    soluzione: 'Risposte curate e tempestive a ogni recensione.' },
  { id: 'g_recenti', area: 'gbp', peso: 1, impatto: 2, nome: 'Recensioni recenti (ultimi 3 mesi)',
    perche: 'Recensioni vecchie fanno pensare a un’attività poco frequentata.',
    soluzione: 'Richiesta di recensione costante, non occasionale.' },

  // ── Sicurezza e conformità ───────────────────────────────────────────────
  { id: 'c_https', area: 'sicurezza', peso: 3, impatto: 3, nome: 'Connessione sicura (HTTPS)',
    perche: 'Senza, il browser mostra “Non sicuro” accanto al vostro nome.',
    soluzione: 'Certificato SSL e connessione cifrata ovunque.' },
  { id: 'c_redirect', area: 'sicurezza', peso: 1, impatto: 2, nome: 'Passaggio automatico da http a https',
    perche: 'Chi digita l’indirizzo a mano deve arrivare sempre alla versione sicura.',
    soluzione: 'Reindirizzamenti corretti di dominio e www.' },
  { id: 'c_ssl', area: 'sicurezza', peso: 1, impatto: 2, nome: 'Certificato SSL valido',
    perche: 'Un certificato scaduto blocca il sito con un avviso rosso.',
    soluzione: 'Rinnovo automatico e monitoraggio del certificato.' },
  { id: 'c_header', area: 'sicurezza', peso: 1, impatto: 1, nome: 'Protezioni di sicurezza del server',
    perche: 'Riducono il rischio di attacchi e di contenuti iniettati.',
    soluzione: 'Configurazione delle intestazioni di sicurezza.' },
  { id: 'c_misto', area: 'sicurezza', peso: 1, impatto: 1, nome: 'Nessun contenuto non protetto',
    perche: 'Elementi caricati senza https fanno perdere il lucchetto.',
    soluzione: 'Tutte le risorse servite in https.' },
  { id: 'c_privacy', area: 'sicurezza', peso: 2, impatto: 2, nome: 'Informativa privacy raggiungibile',
    perche: 'È obbligatoria per il GDPR se raccogliete dati o usate statistiche.',
    soluzione: 'Informativa privacy e cookie aggiornate.' },
  { id: 'c_cookie', area: 'sicurezza', peso: 2, impatto: 2, nome: 'Consenso ai cookie (GDPR)',
    perche: 'Strumenti di tracciamento senza consenso espongono a sanzioni.',
    soluzione: 'Banner di consenso conforme alle linee guida del Garante.' },
  { id: 'c_piva', area: 'sicurezza', peso: 2, impatto: 2, nome: 'Partita IVA visibile nel sito',
    perche: 'Per le attività italiane è un obbligo di legge (art. 35 DPR 633/72).',
    soluzione: 'Dati aziendali completi nel footer di ogni pagina.' },
  { id: 'c_tecnica', area: 'sicurezza', peso: 1, impatto: 1, nome: 'Buone pratiche tecniche ed errori',
    perche: 'Errori nascosti e librerie datate rendono il sito fragile.',
    soluzione: 'Codice pulito, aggiornato e monitorato.' },

  // ── Contatti e integrazioni ──────────────────────────────────────────────
  { id: 'v_cta', area: 'conversione', peso: 2, impatto: 3, nome: 'Invito all’azione nella prima schermata',
    perche: 'Chi arriva deve capire subito cosa fare: chiamare, venire, scrivere.',
    soluzione: 'Prima schermata progettata attorno a un’azione chiara.' },
  { id: 'v_form', area: 'conversione', peso: 1, impatto: 2, nome: 'Modulo di contatto o appuntamento',
    perche: 'Raccoglie le richieste anche quando il negozio è chiuso.',
    soluzione: 'Modulo di richiesta appuntamento o preventivo.' },
  { id: 'v_mappa', area: 'conversione', peso: 1, impatto: 2, nome: 'Mappa e indicazioni stradali',
    perche: 'Porta il cliente dal telefono alla vostra porta in un tocco.',
    soluzione: 'Mappa e pulsante “Indicazioni”.' },
  { id: 'v_orari', area: 'conversione', peso: 1, impatto: 1, nome: 'Orari di apertura sul sito',
    perche: 'È una delle informazioni più cercate prima di una visita.',
    soluzione: 'Orari sempre visibili e sincronizzati con Google.' },
  { id: 'v_social', area: 'conversione', peso: 1, impatto: 1, nome: 'Collegamenti a Instagram e social',
    perche: 'Il sito e i social devono rimandarsi a vicenda.',
    soluzione: 'Integrazione dei social, anche con feed nel sito.' },
  { id: 'v_recensioni', area: 'conversione', peso: 1, impatto: 2, nome: 'Recensioni mostrate nel sito',
    perche: 'La fiducia costruita su Google deve vedersi anche sul sito.',
    soluzione: 'Sezione recensioni collegata a Google.' },
  { id: 'v_catalogo', area: 'conversione', peso: 1, impatto: 2, nome: 'Vetrina prodotti o shop online',
    perche: 'Chi cerca un regalo vuole vedere cosa trova prima di uscire.',
    soluzione: 'Vetrina delle collezioni o e-commerce.' },
  { id: 'v_statistiche', area: 'conversione', peso: 1, impatto: 2, nome: 'Statistiche delle visite',
    perche: 'Senza dati non sapete quante persone vi cercano e da dove.',
    soluzione: 'Google Analytics 4 e Search Console configurati.' },
  { id: 'v_campagne', area: 'conversione', peso: 1, impatto: 1, nome: 'Pronto per campagne pubblicitarie',
    perche: 'Pixel e tag servono a misurare Instagram e Google Ads.',
    soluzione: 'Meta Pixel e tag Google Ads, con consenso.' },
  { id: 'v_aggiornato', area: 'conversione', peso: 1, impatto: 1, nome: 'Sito aggiornato di recente',
    perche: 'Un anno vecchio nel footer fa pensare a un’attività trascurata.',
    soluzione: 'Manutenzione e contenuti aggiornati con continuità.' },
];

export const STATI = {
  ok: { etichetta: 'OK', valore: 1 },
  warn: { etichetta: 'Da migliorare', valore: 0.5 },
  bad: { etichetta: 'Critico', valore: 0 },
  na: { etichetta: 'Non rilevato', valore: null },
};
